[ServiceInfo] fix when not play service
File "/usr/lib/enigma2/python/Screens/Screen.py", line 93, in execBegin

File "/usr/lib/enigma2/python/Screens/ServiceInfo.py", line 190, in
ShowServiceInformation
  File
"/usr/lib/enigma2/python/Screens/ServiceInfo.py", line 224, in
getTrackList
AttributeError: 'NoneType' object has no attribute
'getCurrentTrack'

(cherry picked from commit 0dcb2dc389f81126ef5d165b2ec8e07d7d71b7a3)