picload: use str::to_string instead snprintf
That commit should fix the following gcc warning:
gdi/picload.cpp:25:27: error: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Werror=format-truncation=]

(cherry picked from commit 0288f81f78c4a3c8a016e0e875a872d4f6965335)