[ImageManager.py] Fix Py3 'str' -> 'bytes' issue
______________________________________

<    84.9584> 14:48:26.2581 Traceback (most recent call last):
<    84.9585> 14:48:26.2582   File "/usr/lib/enigma2/python/StartEnigma.py", line 252, in processDelay
<    84.9594> 14:48:26.2590     callback(*retval)
<    84.9595> 14:48:26.2592   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ViX/ImageManager.py", line 1444, in doDownloadX
<    84.9644> 14:48:26.2640     headers, fileurl = self.processAuthLogin(currentSelected[0][1])
<    84.9645> 14:48:26.2641   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/ViX/ImageManager.py", line 1476, in processAuthLogin
<    84.9673> 14:48:26.2670     base64string = base64.b64encode('%s:%s' % (username, password))
<    84.9674> 14:48:26.2671   File "/usr/lib/python3.8/base64.py", line 58, in b64encode
<    84.9686> 14:48:26.2683     encoded = binascii.b2a_base64(s, newline=False)
<    84.9688> 14:48:26.2685 TypeError: a bytes-like object is required, not 'str'

________________________________________________________

<  4770.5075> 16:06:32.3588 Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.8/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/usr/lib/enigma2/python/e2reactor.py", line 194, in _doReadOrWrite
    why = selectable.doWrite()
  File "/usr/lib/python3.8/site-packages/twisted/internet/tcp.py", line 627, in doConnect
    self._connectDone()
  File "/usr/lib/python3.8/site-packages/twisted/internet/tcp.py", line 656, in _connectDone
    self.protocol.makeConnection(self)
  File "/usr/lib/python3.8/site-packages/twisted/internet/protocol.py", line 514, in makeConnection
    self.connectionMade()
  File "/usr/lib/python3.8/site-packages/twisted/web/client.py", line 102, in connectionMade
    self.sendHeader(key, value)
  File "/usr/lib/python3.8/site-packages/twisted/web/http.py", line 533, in sendHeader
    santizedName = _sanitizeLinearWhitespace(name)
  File "/usr/lib/python3.8/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
    return b' '.join(headerComponent.splitlines())
builtins.TypeError: sequence item 0: expected a bytes-like object, str found