object: fix compile when using exceptions
Compiling with exceptions enable clang fails with the following error:
In file included from actions/action.cpp:2:
../lib/base/init.h:120:8: error: 'operator delete' is a protected member of 'iObject'
                        t = new T1();
                            ^~~
../lib/base/init.h:136:2: note: in instantiation of member function 'eAutoInitPtr<eActionMap>::initNow' requested here
        eAutoInitPtr(int runl, const char *description): eAutoInit(runl, description), t(nullptr)
        ^
actions/action.cpp:323:26: note: in instantiation of member function 'eAutoInitPtr<eActionMap>::eAutoInitPtr' requested here
eAutoInitPtr<eActionMap> init_eActionMap(eAutoInitNumbers::actions, "eActionMap");
                         ^
../lib/base/object.h:20:7: note: declared protected here
        void operator delete(void *p) { ::operator delete(p); }
             ^

We should mark operator delete protected only when we are not using __EXCEPTIONS.

(cherry picked from commit 29a93d7244a9246a8c81eb34639a798deab60923)