use c++11 struct initializer
This commit uses the new c++11 brace zero initialization and silences the follwing warings:
dvb/dvbtime.cpp:105:11: error: missing field 'tm_min' initializer [-Werror,-Wmissing-field-initializers]
        tm t = {0};
                 ^

(cherry picked from commit 1283d41290f60bf65812f97e42418d97b38a0e34)