python: use newer C99 initializer on PyTypeObject
This commit users newer C99 initializer syntax on PyTypeObject as proposed in https://pythoncapi.readthedocs.io/type_object.html
Also it fixes the following warnings:
python/enigma_python.cpp:5066:1: error: missing field 'tp_free' initializer [-Werror,-Wmissing-field-initializers]
};
^

(cherry picked from commit 3c6c3b5e05995d0f103fae6c394159e5ee3a9787)