lib/gdi/picload.cpp: Fix build fail on typedef boolean and TRUE
Solve the following build error:

lib/gdi/picload.cpp:426:30: error: invalid conversion from 'int' to 'boolean' [-fpermissive]
  jpeg_read_header(ciptr, TRUE);

jpeglib.h does "typedef boolean" unless you set HAVE_BOOLEAN. But a boolean typedef
apparently is not the same as an int according to more recent GCC versions. Work
around the issue by using a #define instead of a typedef.