Temporary workaround for BS on stopping a transcoded stream taken from OpenATV: https://github.com/openatv/enigma2/commit/4265bb2a10248be6800cf57ec990657b7f322bf9#diff-218f9e2be7b25cd537872b6c6fe2d13a
< 75485.120> [StreamService] execEnd 1:0:19:28A7:68:F020:FFFF0000:0:0:0:
< 75485.120> [eDVBServiceRecord] stop recording!
< 75485.120> [eDVBServiceRecord] fetching cutlist failed because tstools failed
< 75485.121> Traceback (most recent call last):
< 75485.121>   File "/usr/lib/enigma2/python/Navigation.py", line 98, in dispatchRecordEvent
< 75485.121>   File "/home/vix/oe-alliance/builds/openvix/release/vuultimo4k/tmp/work/all-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-1.2+gitAUTOINC+7bfbaaee78-r0/git/plugin/controllers/stream.py", line 54, in requestWrite
< 75485.121>   File "/usr/lib/python2.7/site-packages/twisted/web/server.py", line 220, in write
< 75485.121>   File "/usr/lib/python2.7/site-packages/twisted/web/http.py", line 957, in write
< 75485.122> AttributeError: 'NoneType' object has no attribute 'write'