Subservices: Solve possible GSOD when switching eg to HDMI-in
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Navigation.py", line 69, in dispatchEvent
    x(i)
  File "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
    func[1](ev)
  File "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
    self.changed((self.CHANGED_SPECIFIC, event))
  File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
    self.downstream_elements.changed(*args, **kwargs)
  File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
    x(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/Converter/ServiceInfo.py", line 235, in changed
    Converter.changed(self, what)
  File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
    self.downstream_elements.changed(*args, **kwargs)
  File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
    x(*args, **kwargs)
  File "/usr/lib/enigma2/python/Components/Converter/ConditionalShowHide.py", line 41, in changed
    vis = self.calcVisibility()
  File "/usr/lib/enigma2/python/Components/Converter/ConditionalShowHide.py", line 34, in calcVisibility
    b = self.source.boolean
  File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
    cache[name] = (True, f(self))
  File "/usr/lib/enigma2/python/Components/Converter/ServiceInfo.py", line 132, in getBoolean
    return hasActiveSubservicesForCurrentChannel(service)
  File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 178, in hasActiveSubservicesForCurrentChannel
    activeSubservices = getActiveSubservicesForCurrentChannel(service)
  File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 169, in getActiveSubservicesForCurrentChannel
    if not activeSubservices:

UnboundLocalError: local variable 'activeSubservices' referenced before assignment
(cherry picked from commit 355d70d3120f9a77d6e3dcef3e9341d37743b7d7)