Revert "action.cpp/h OpenPLI changes"
This reverts commit 2a88a7e46629610608d25e1f2e97c7e76e7a3c78.

_______________________________________________________________________

The reverted commit deletes "unbindNativeKey" but this attribute is used by ButtonSetup.py and ChannelSelection.py.

https://github.com/OpenViX/enigma2/blob/Dev/lib/python/Screens/ButtonSetup.py#L230-L233
https://github.com/OpenViX/enigma2/blob/Dev/lib/python/Screens/ChannelSelection.py#L2661-L2662

This will cause a BSoD...
"AttributeError: 'eActionMap' object has no attribute 'unbindNativeKey'"

Please make the necessary changes to the Python files so the original commit can be reinstated.