Revert "[config.py] __getattr_ method, sanity test and exception"
This reverts commit 7a400688da86b87aea20ac97f0e76f7b1213656b.

This commit is linked to an OWI crash. Reverted until further investigated.

File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/web.py", line 17, in
from models.services import getCurrentService, getBouquets, getServices, getSubServices, getSatellites, getBouquetEpg, getBouquetNowNextEpg, getServicesNowNextEpg, getSearchEpg, getChannelEpg, getNowNextEpg, getSearchSimilarEpg, getAllServices, getPlayableServices, getPlayableService, getParentalControlList, getEvent, loadEpg, saveEpg
File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/services.py", line 25, in
from Plugins.Extensions.OpenWebif.local import tstrings # using the tstrings dic is faster than translating with _ func from init
File "/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/local.py", line 8, in
AT_unit = config.plugins.autotimer.unit.value == "hour" and _("hour") or _("minute")
File "/usr/lib/enigma2/python/Components/config.py", line 1665, in getattr
AttributeError: Error: Attribute not defined!