estring: fix bug in replace_all
This commit fixes the following warning discovered using clang.
base/estring.cpp:902:20: error: result of comparison of constant 128 with expression of type '__gnu_cxx::__alloc_traits<std::allocator<char>, char>::value_type' (aka 'char') is always true
      [-Werror,-Wtautological-constant-out-of-range-compare]
                        if (out.at(loc) < 0x80)
                            ~~~~~~~~~~~ ^ ~~~~

(cherry picked from commit fd5afae41eeb5ee85630bbef3febcaadcff710e6)