config: Ensure in ConfigDelection that always a string is returned
to avoid e.g. errors like TypeError: 'bool' object has no attribute '__getitem__'

(cherry picked from commit 7a113a28bb6e32d1ae89281525202f2d2ec67643)