Revert "[SkinSelector] Delete embedded screen."
This reverts commit dcf7eaf0c4bb62cad2ffb6ba42938ffbf301ed59.

This is reverted as it causes a BSoD.

< 27511.3512> Traceback (most recent call last):
< 27511.3513>   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 72, in action
< 27511.3514>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 297, in keyNumberGlobal
< 27511.3515>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 79, in okbuttonClick
< 27511.3516>   File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
< 27511.3517>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 93, in runScreen
< 27511.3518>   File "/usr/lib/enigma2/python/Screens/Menu.py", line 99, in openDialog
< 27511.3519>   File "/usr/lib/enigma2/python/mytest.py", line 324, in openWithCallback
< 27511.3522>     dlg = self.open(screen, *arguments, **kwargs)
< 27511.3522>   File "/usr/lib/enigma2/python/mytest.py", line 334, in open
< 27511.3524>     dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
< 27511.3525>   File "/usr/lib/enigma2/python/mytest.py", line 271, in instantiateDialog
< 27511.3527>     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
< 27511.3527>   File "/usr/lib/enigma2/python/mytest.py", line 301, in doInstantiateDialog
< 27511.3529>     dlg.applySkin()
< 27511.3530>   File "/usr/lib/enigma2/python/Screens/Screen.py", line 239, in applySkin
< 27511.3531>   File "/usr/lib/enigma2/python/Screens/Screen.py", line 270, in createGUIScreen
< 27511.3532>   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 64, in layoutFinished
< 27511.3533>     self.refreshList()
< 27511.3533>   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 130, in refreshList
< 27511.3535>     self.loadPreview()
< 27511.3535>   File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 135, in loadPreview
< 27511.3536>     preview = self.currentEntry[7]
< 27511.3537> TypeError: 'bool' object has no attribute '__getitem__'