Revert "[ChannelSelection] Use fallback if no network time and not on DVB service (#183)"
This reverts commit fcf2ea2c388b06d8c4947df3e535bf45af94cfcc.

This has been reverted due to BSoD.

<   494.582> [NetworkTime] setting E2 time: 1503243928.79
<   494.701> [ChannelSelection] invalid service or time not set and not on a DVB service - try to use fallback DVB service
<   494.701> Traceback (most recent call last):
<   494.701>   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2139, in __onCreate
<   494.702>   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2146, in findFallbackService
<   494.702>   File "/usr/lib/enigma2/python/Screens/ChannelSelection.py", line 2192, in findServiceBouquet
<   494.702> AttributeError: 'bool' object has no attribute 'valid'
<   494.702> [ePyObject] (CallObject(<bound method ChannelSelection.__onCreate of <class 'Screens.ChannelSelection.ChannelSelection'>>,()) failed)

For more info please see comments in the original commit.