config: Solve possible GSOD
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 210, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 100, in menuClosedWithConfigFlush
    configfile.save()
  File "/usr/lib/enigma2/python/Components/config.py", line 1807, in save
    config.saveToFile(self.CONFIG_FILE)
  File "/usr/lib/enigma2/python/Components/config.py", line 1777, in saveToFile
    text = self.pickle()
  File "/usr/lib/enigma2/python/Components/config.py", line 1739, in pickle
    return ''.join(result)
TypeError: sequence item 990: expected string, bool found

(cherry picked from commit b4b4cd222e81b2f38b79fd1e25a955982acb2c82)