eServiceMP3: change m_decoder into smart pointer
It seems that older GCC 4.8 fails to compile with the following error:

../lib/base/object.h: In destructor "virtual eServiceMP3::~eServiceMP3():"
../lib/base/object.h:20:7: error: "static void iObject::operator delete(void*)" is protected
  void operator delete(void *p) { ::operator delete(p); }

Changing to smart pointer fixes the error.