eptrlist: fix forward declaration on clang
When using clang the eptrlist fails with the following message:
In file included from ../../../../../../lib/base/ebase.h:12:
../../../../../../lib/base/eptrlist.h:118:26: error: variable has incomplete type 'ePtrList::iterator'
        iterator erase(iterator it)
                                ^
../../../../../../lib/base/eptrlist.h:24:8: note: forward declaration of 'ePtrList::iterator'
        class iterator;
              ^

Delaring iterators out of class fixes the issue.

(cherry picked from commit 471b0b1a038d14e51eb78df54c2c05cc05fc5cd6)