Solve bug introduced in b6de676d
Thanks for reporting Dimitrij

raceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 207, in processDelay
    callback(*retval)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/VideoTune/VideoFinetune.py", line 403, in testpicCallback
    self.next()
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/VideoTune/VideoFinetune.py", line 391, in testpic_uhd
    self.session.openWithCallback(self.testpicCallback, FullUHDTestScreen)
  File "/usr/lib/enigma2/python/mytest.py", line 286, in openWithCallback
    dlg = self.open(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 296, in open
    dlg = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/mytest.py", line 239, in instantiateDialog
    return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
  File "/usr/lib/enigma2/python/mytest.py", line 256, in doInstantiateDialog
    dlg = screen(self, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/VideoTune/VideoFinetune.py", line 85, in __init__
    Console().ePopen("/usr/bin/showiframe %s") % resolveFilename(SCOPE_PLUGINS, "SystemPlugins/VideoTune/testbeeld-4k.mvi")
TypeError: unsupported operand type(s) for %: 'instance' and 'str'

(cherry picked from commit cfaa4fc47b9d2c0d247268e8e65692c3900fdfb6)