decoded: bring back obsolete dvb API's
This commit will fix the following errors when building using Ubuntu 20.04.
dvb/decoder.cpp:230:21: error: ‘AUDIO_GET_PTS’ was not declared in this scope
dvb/decoder.cpp:657:19: error: ‘VIDEO_GET_FRAME_RATE’ was not declared in this scope

Above API's removed from kernel on the following commits:
https://github.com/torvalds/linux/commit/b41e44b4cb230747d7ad56e38c9dc65369b1d381
https://github.com/torvalds/linux/commit/d21c249b26311dd193b100e65fc9e7ae96233d40