actions: add missing initializer on call_entry constructor
This commit should fix the following gcc warning:
actions/action.cpp:187:8: error: ‘<anonymous>.call_entry::m_widget_arg2’ may be used uninitialized in this function [-Werror=maybe-uninitialized]