configure: Add no-error=stringop-truncation
Disable stringop-truncation error because it happens on swig that is out of our control.

In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘void SWIG_Python_FixMethods(PyMethodDef*, swig_const_info*, swig_type_info**, swig_type_info**)’ at python/enigma_python.cpp:59122:22:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying 10 bytes from a string of the same length [-Werror=stringop-truncation]

It seems that swig 3.0.12 is missing the following patch: https://github.com/swig/swig/pull/898
Above patch is already available on Zeus OE so it's producing the error, although Gihbub Actions using Ubuntu 18.04 does.