[UsageConfig] fix not str default value
File "/usr/lib/enigma2/python/Components/ConfigList.py", line 271, in
keyFile
File "/usr/lib/enigma2/python/Screens/ChoiceBox.py", line 221, in
updateSummary
TypeError: cannot concatenate 'str' and 'NoneType' objects

(cherry picked from commit 7314031f2c10dba3bf762b5d195313b8e1c0450a)